apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - users.yaml
  - orders.yaml
  - httproutes.yaml
  - waypoint.yaml
  - authorization-policy.yaml
